# Generated by Django 4.1.5 on 2023-01-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.CharField(blank=True, max_length=150, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
