# Generated by Django 4.1.5 on 2023-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('group', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
