# Generated by Django 4.1.5 on 2023-01-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
