# Generated by Django 4.1.5 on 2023-01-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_about_me_contact_education_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_me',
            old_name='current_loaction',
            new_name='current_loacation',
        ),
    ]
